ingestion:
  topic: kafkasampler-raw-tweets

sanitizing:
  topic: kafkasampler-sanitized-tweets

analyzing:
  topic: kafkasampler-analyzed-tweets

streaming:
  applicationId: twitter-sentiment-analysis
  zookeeperUrl: localhost:2181
  brokerUrl: localhost:9092
