/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.kafkasampler.gtd.persistence.serialization;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ItemConcluded extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1911355423732256450L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemConcluded\",\"namespace\":\"net.mguenther.kafkasampler.gtd.persistence.serialization\",\"fields\":[{\"name\":\"itemId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String itemId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemConcluded() {}

  /**
   * All-args constructor.
   * @param itemId The new value for itemId
   */
  public ItemConcluded(java.lang.String itemId) {
    this.itemId = itemId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return itemId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: itemId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'itemId' field.
   * @return The value of the 'itemId' field.
   */
  public java.lang.String getItemId() {
    return itemId;
  }

  /**
   * Sets the value of the 'itemId' field.
   * @param value the value to set.
   */
  public void setItemId(java.lang.String value) {
    this.itemId = value;
  }

  /**
   * Creates a new ItemConcluded RecordBuilder.
   * @return A new ItemConcluded RecordBuilder
   */
  public static net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder newBuilder() {
    return new net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder();
  }

  /**
   * Creates a new ItemConcluded RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemConcluded RecordBuilder
   */
  public static net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder newBuilder(net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder other) {
    return new net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder(other);
  }

  /**
   * Creates a new ItemConcluded RecordBuilder by copying an existing ItemConcluded instance.
   * @param other The existing instance to copy.
   * @return A new ItemConcluded RecordBuilder
   */
  public static net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder newBuilder(net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded other) {
    return new net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder(other);
  }

  /**
   * RecordBuilder for ItemConcluded instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemConcluded>
    implements org.apache.avro.data.RecordBuilder<ItemConcluded> {

    private java.lang.String itemId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ItemConcluded instance
     * @param other The existing instance to copy.
     */
    private Builder(net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'itemId' field.
      * @return The value.
      */
    public java.lang.String getItemId() {
      return itemId;
    }

    /**
      * Sets the value of the 'itemId' field.
      * @param value The value of 'itemId'.
      * @return This builder.
      */
    public net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder setItemId(java.lang.String value) {
      validate(fields()[0], value);
      this.itemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'itemId' field has been set.
      * @return True if the 'itemId' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'itemId' field.
      * @return This builder.
      */
    public net.mguenther.kafkasampler.gtd.persistence.serialization.ItemConcluded.Builder clearItemId() {
      itemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ItemConcluded build() {
      try {
        ItemConcluded record = new ItemConcluded();
        record.itemId = fieldSetFlags()[0] ? this.itemId : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
