version: '2'
services:
  zookeeper:
    image: kafka-sampler/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: kafka-sampler/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  elasticsearch-int:
    image: elasticsearch:5
    ports:
      - 9200:9200
      - 9300:9300
  kibana-int:
    image: kibana:5
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-int:9200
